### ISSUE TITLE
Implement an in-app saving and export function for badges

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#15]
Currently badges cannot be saved. Please add a save button. It would make it easier if the user does not necessarily has to add a name. However the name of the saved file  - it should be possible to change it. Also ensure the user can export the saved file and open it e.g. on another phone.

**Comment by ark786** [comment]
I would like to work on it. Please assign it to me.

**Comment by mariobehling** [comment]
There is no need to assign issues. It is sufficient if you claim it here. Please go ahead.

**Comment by yatri1609** [comment]
I would like to implement this

**Comment by yatri1609** [comment]
@mariobehling Do we want to log data to csv fiile or any other file type?

**Comment by iamareebjamal** [comment]
Use https://github.com/square/tape

**Comment by yatri1609** [comment]
@iamareebjamal I have a few doubts regarding the saving of badge. I wanted to know in which format do we want to save the preview?

**Comment by iamareebjamal** [comment]
Why do we need to save preview?

**Comment by yatri1609** [comment]
Sorry not preview the badge. My bad! @iamareebjamal

**Comment by iamareebjamal** [comment]
JSON, as discussed on the preview. Serialized using tape

**Comment by adityastic** [comment]
This issue has been occupied since long time, can I also implement my own version of it using gson or moshi ? @iamareebjamal

**Comment by iamareebjamal** [comment]
Go ahead, use moshi

**Comment by adityastic** [comment]
@iamareebjamal thank you

**Comment by adityastic** [comment]
@iamareebjamal I also need advice regarding the navigation options inside the app. As the save and export feature need to have a recycler view to give the ability to display and select the saved configuration should I use tablayout, viewpager with indicator, navigation drawer or bottombar. Please suggest me the preferred and perfect option for this scenario

**Comment by iamareebjamal** [comment]
For now, just an icon in the action bar will do

**Comment by adityastic** [comment]
@iamareebjamal alright sir

**Comment by adityastic** [comment]
@iamareebjamal Sorry for the late reply, I was having an exam today. So here is a sneak peak of what I have created.

![ezgif com-video-to-gif-4](https://user-images.githubusercontent.com/11988517/56423385-773dd400-62c9-11e9-861b-258dd261cedb.gif)

**NOTE: On loading the configuration, we cannot recover the text or the drawable selected**

Features:
1. Can share configuration
2. Can save and load configurations
3. Can import configurations by opening the txt from our application

Issues:
1. Not able to send the configuration to the badge because of the other options.
2. We cannot convert hexadecimal to characters or drawables. Therefore, the selected configuration will not load in the edittext or the drawable recyclerview
3. Send function currently sends the hexadecimal strings from the edittext or the recyclerview. we need to create another radio as loaded config in order to send the data. This will make the workflow fairly complex. 

Suggested Fixes:
- To keep a single instance of the badge preview on top of the screen and have 2 scrollable sections below the badge
  1. First Section will be same like the current screen.
  2. Second Section will contain the names of all the saved, imported configurations. you will be able to select one only one configuration at a time, Just like the drawable adapter. So on selecting that configuration, you will see the preview on the preview badge.

**Comment by adityastic** [comment]
@iamareebjamal please share on thoughts on this sir.

**Comment by iamareebjamal** [comment]
I don't think each badge should be kept in a separate file. I think several bades can be grouped in one file. Like a sticker pack. @mariobehling can clear this up

**Comment by adityastic** [comment]
@iamareebjamal yes that can be done, but we have an issue with sending the data to the device in this case. It is because we cannot convert the hexadecimals back to the text. we need a separate section which does not depend on text or drawables.

**Comment by iamareebjamal** [comment]
Why can't we convert hexadecimals to text?

**Comment by yatri1609** [comment]
@mariobehling @CloudyPadmal @iamareebjamal I was already working on this issue. So kindly let me work on this. Just because I have end semester exams doesn't mean I am not working on it.

**Comment by adityastic** [comment]
@iamareebjamal currently the preview and the hardware accepts hexadecimal arrays. We convert the text or drawable to hexadecimal strings using our helper classes. We do not save the text or the position of the drawable because that would not be feasible, therefore we save the hexadecimal string itself. Now, if we want to convert the hexadecimal strings to text or drawable, we would have to brute force combinations based on the hexadecimal strings. And if in future we plan to add more drawables in the app, that would be very bad for the app, sir. I could create a mock-up with a new design which can handle this issue prominently, if you wish. Let me know your feedback on this sir

**Comment by iamareebjamal** [comment]
So why not save the text and not hexadecimal string?

Also, why is the conversion of text a one way function?

**Comment by adityastic** [comment]
@iamareebjamal if we save the text that will not be generic. Hexadecimal strings are the general form which is same for both text and drawables.

Conversion of text is not a one way function, neither is convertion of drawables. But when you get the Hexadecimal strings from the file, you first need to interpret whether it is a text or a drawable. If it is a drawable, we need to create Hexadecimal of all the available drawables and check if the stored hexadecimal strings match with the one generated with the drawable. If in the future we plan to add custom drawables from the user, this method will become redundant

**Comment by adityastic** [comment]
As when a user shares a custom drawable which is not currently present in the app, it will not be able to select that drawable, as it is not present inside the app. But we want to support people sharing and creating custom text or drawable

**Comment by adityastic** [comment]
Therefore if we create another section that targets the hexadecimal strings directly, these hexadecimal strings are the base of both text and drawable, this section would be able to handle any hexadecimal string including custom drawables or texts

**Comment by adityastic** [comment]
@iamareebjamal should I move forward with this idea sir?. I will assure you to create something which will help in the betterment of this application

**Comment by iamareebjamal** [comment]
I'll understand the issue with one way conversion first and then move ahead. You can continue with generic implementation

**Comment by adityastic** [comment]
@iamareebjamal Great Sir, I will go ahead and create a demo application which will portray how the different section will work. Thank you for your time

**Comment by adityastic** [comment]
@iamareebjamal This is the progress so far.
![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/11988517/56472870-a9923180-6481-11e9-98a6-dc998674b193.gif)

Features:
[x] Save Shapes or Texts
[x] Sharing Shapes or Texts with Friends using any medium that supports txt files
[x] Import Shared Files using the + button in the action bar
[x] A Separate Section to Handle Saved or Imported files
[x] Send Button is now a Floating Button which works according to the selected viewpager
[x] Chips denote the attributes of the saved config

Let me know your feedback on this sir, If you like it I can drop a pull request for this issue.
Regards

**Comment by adityastic** [comment]
@yashk2000 @naman653 @ShridharGoel let me know your feedback on this

**Comment by yashk2000** [comment]
@adityastic looks good. After you load a saved badge and click the send button, is data sent to the device?

**Comment by adityastic** [comment]
@yashk2000 it works, you can try it yourself. https://github.com/adityastic/badge-magic-android/tree/saveexport?files=1

**Comment by yashk2000** [comment]
@iamareebjamal @adityastic it works well.

**Comment by adityastic** [comment]
Great. Let's wait for @iamareebjamal sir to reply

**Comment by iamareebjamal** [comment]
Send a PR

**Comment by adityastic** [comment]
@iamareebjamal on it
