### ISSUE TITLE
Discussion on UI/UX design + navigation of the app

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/badge-magic-android#207]
Currently, the latest update of the app contains some component that I find not really user-friendly, at least when I see myself as a user.
1. I took me a while to realize that FAB button is used to send the text/drawable + there is no indication of sending, especially on sending empty text or drawables (a toast is already ok). Personally, I prefer the old "SEND" button to this one. I think there is also discussion on FAB as not a good design component
2. It's not clear for first time user to find the saved configurations (it is navigated by swiping right with a view pager). My suggestion is to create a new fragment for saved configurations and navigate to it by an icon in the action bar.
3. It's not clear for me what is the use of "+" adding action button in the action bar at first until I take a look at the latest PR. And I'm really sure if this adding action button is really useful.
4. The app needs horizontal variations. I have attached my mockups in the GSoC proposal. Please give some comments or maybe if you guys also have some other mockups, I would love to see it.

**Screenshots**
This is my initial mockups on GSoC so it is not polished
<img src="https://i.ibb.co/SvQJj1k/Mockup-Magic-Badge-01.jpg" width="300">
<img src="https://i.ibb.co/fNbFVjm/Mockup-Magic-Badge-02.jpg" height="300">
<img src="https://i.ibb.co/NpqP2xc/Mockup-Magic-Badge-04.jpg" width="300">

Please give some thoughts @adityastic @yashk2000 @yatri1609 . And if there are other problems on this topic, please also comment.

**Comment by adityastic** [comment]
@anhanh11001 I Included the FAB Button because I had to send the configuration according to the selected viewpager item. If we get back the send button, we need to have a button which is present on both the fragments. FAB button made it a lot easier

*Issues if we create separate activity for saved configurations*
- you cannot recover the text or drawable from the hexadecimal strings. Hexadecimal strings are the base of both text and drawable. You can save and render any shape if you know the hexadecimal string of that shape. Text and Drawables are nothing but shapes in hexadecimal.
- when you try to select the saved data in another  activity, there has to be a mechanism to display it in the parent activity, which can only be done by including another section which is what I did.

The + icon in the top is to import a configuration. It lets you import the badge configuration from the device storage. Whereas, I also have added the mimeType which lets you pick configuration from any app.

*Perks of the current layout*
- You can import any shape which is not even present inside the application. 

*Cons in the current layout*
- The Saved Configuration is kind of hidden, a navigation option like a bottombar would be a nice feature to add.

I'm sure I might have confused you, Let me know your thoughts on this. BTW I did create something similar which can be found here #15 . These issues where listed there also, have a look

**Comment by adityastic** [comment]
@anhanh11001 an animation with the fab while sending would be a great idea though

**Comment by adityastic** [comment]
@anhanh11001 I've proposed to add a bottom bar, let me know your thoughts on it

**Comment by anhanh11001** [comment]
I think a bottom bar is a good solution

**Comment by anhanh11001** [comment]
I get your point on FAB now, then I'll think on a solution. I think a toast message is ok but some kind of loading indicator should be better.

**Comment by adityastic** [comment]
@anhanh11001 yes sir, animations ftw

**Comment by adityastic** [comment]
Ohk, so after Fab Animation and Bottom Bar what else can be improved? Suggestions plz @yashk2000 @anhanh11001

**Comment by adityastic** [comment]
@shridhargoel

**Comment by adityastic** [comment]
@yatri1609

**Comment by adityastic** [comment]
@theLimitBreaker

**Comment by mariobehling** [comment]
Thanks! Good input. Some things are already in progress. Please open specific issues for anything outstanding. Closing this therefore. Cheers.
