### ISSUE TITLE
Invert LED effect should have a pixel line at beginning of word

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badge-magic-android#356]
Using the invert LED effect with a number of characters appears strange as the beginning of the character is transparent just as the empty space before. Expected: Add a line of lighted pixels before.

![Screenshot_2019-06-07-15-57-56-700_org fossasia badgemagic](https://user-images.githubusercontent.com/1583873/59109587-9659f900-893d-11e9-822a-7bb4576bd9a8.png)

**Comment by adityastic** [comment]
@mariobehling we cannot add a single line of pixels. In Order to add a single line of lighted pixels, we would have to add a total of 8 pixels in the very start, 7 transparent and 1 lighted. That will create 7 extra spacings in the front. The Badge accepts a 22bit hexadecimal string, and it has to be 22bits. we cannot make it less

**Comment by iamareebjamal** [comment]
@adityastic Ok, add as many lines which bound the starting character

**Comment by adityastic** [comment]
@iamareebjamal i did not get what you mean by, add as many lines. Please elaborate

**Comment by iamareebjamal** [comment]
There should be red color line/s on left of letter M

**Comment by adityastic** [comment]
@mariobehling please shift it to next week's milestone. I need to add some intelligent algorithm which knows when to add a line and when to not.
